spring:
  application:
    name: resource-service
  rabbitmq:
    host: ${RESOURCE_RABBIT_HOST}
    port: ${RESOURCE_RABBIT_PORT}
    username: ${RESOURCE_RABBIT_USER}
    password: ${RESOURCE_RABBIT_PASSWORD}

service-api.enabled: false
